const puppeteer = require("puppeteer");
const {Session } = require("./src/Session");
const {State } = require("./src/State");
const {Util } = require("./src/Util");
const {PlanUnit} = require("./src/PlanUnit");
const {District} = require("./src/District");
let jsonDocument = {};
(async() => {
    const browser = await puppeteer.launch();
    let page = await browser.newPage();    
    const session = new Session(jsonDocument,page);
    let finYears = await session.getSessions();    
    session.updateJsonDocument(finYears);
    const state = new State(page,jsonDocument,"");
    let states = await state.getStates();    
    state.updateJsonDocument(states);
    page = await browser.newPage();   
    const planUnit = new PlanUnit(jsonDocument,page);
    await planUnit.fetchAndSet();
    page = await browser.newPage();         
    const district = new District(jsonDocument,page);
    await district.fetchAndSet(); 
    console.log("File Write Starting");     
    await district.writeFile();   
    console.log("File Write Successfully.");
    process.exit();
})();