const puppeteer = require("puppeteer");
const {Session } = require("./src/Session");
const {State } = require("./src/State");
const {Util } = require("./src/Util");
const {PlanUnit} = require("./src/PlanUnit");
let jsonDocument = {};
(async() => {
    const browser = await puppeteer.launch();
    let page = await browser.newPage();    
    const session = new Session(jsonDocument,page);
    let finYears = await session.getSessions();    
    session.updateJsonDocument(finYears);    
    const state = new State(page,jsonDocument,"","");
    let states = await state.getStates();    
    state.updateJsonDocument(states);    
    page = await browser.newPage();    
    const planUnit = new PlanUnit(jsonDocument,page);
    await planUnit.fetchAndSet("2015-2016");
    console.log("File Write Starting");
    planUnit.writeFile();
    console.log("File Write Successfully.");
})();